# Generated by Django 4.2.6 on 2023-11-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0009_alter_measurement_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
    ]
