# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Груша",
  "description": "Казахстан"
}

###

POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Яблоки",
  "description": "Россия"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/1/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/1/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=пом
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?title=Бананы

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "hngfgbsdsdrhg",
  "positions": [
        {
      "product": 4,
      "quantity": 70,
      "price": 90.30
    },
    {
      "product": 2,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 3,
      "quantity": 100,
      "price": 180
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/21/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 101,
      "price": 130.80
    },
    {
      "product": 3,
      "quantity": 244,
      "price": 145
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=2
Content-Type: application/json

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?search=груш&limit=3&offset=0
Content-Type: application/json